# Generated by Django 3.2.12 on 2024-03-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='nombres_de_questions',
            new_name='nombre_de_questions',
        ),
    ]
